---
sidebar: sidebar 
permalink: task-manage-private-google-cloud.html 
keywords: activate, license, licensing, install, request capacity, link subscription, keystone flex, bluexp, netapp console, marketplace, google cloud 
summary: AWS, Azure, Google Cloud에 대한 일반 및 하이퍼스케일러별 종단 간 개인 제안 프로세스와 NetApp Intelligent Services 수용 및 활성화 가이드를 관리합니다. 
---
= NetApp Console 대한 Google Cloud 비공개 제안 수락 및 구성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 


[role="lead"]
Google Cloud 콘솔의 NetApp Console 목록에 대한 마켓플레이스 비공개 제안을 수락합니다. 콘솔에서 Google Cloud 자격 증명을 구성합니다.

.시작하기 전에
* NetApp 영업팀과 협력하여 비공개 제안을 작성하세요. 귀하의 영업팀에서 귀하에게 제공 링크를 제공해야 합니다.
* 귀하의 결제 계정은 무료 평가판이 아니어야 합니다. 무료 체험 계정에서는 비공개 제안을 받을 수 없습니다. 평가판 청구 계정을 사용하려고 하면 오류가 발생하고 NetApp 클라우드 팀의 도움이 필요합니다.
* 제안을 수락하려면 다음과 같은 Google Cloud 권한이 필요합니다.
+
** `roles/billing.admin`대상 Cloud Billing 계정 또는 Google Cloud 조직에 대해
** `roles/viewer`Cloud Billing 계정으로 청구되는 프로젝트의 경우






== Google Cloud에서 비공개 제안 수락

Google Cloud 프로젝트는 하나의 Marketplace 구독에만 연결될 수 있습니다. 동일한 Google Cloud 프로젝트의 워크로드에 대해 두 가지 다른 구독을 사용하려면 각 구독에 대해 하나씩, 총 두 개의 별도 Console 계정을 만들어야 합니다.

[IMPORTANT]
====
비공개 제안을 활성화하려면 모든 단계를 완료해야 합니다. 단계를 건너뛰면 이중 충전과 같은 문제가 발생할 수 있습니다.

제안 조건, 가격 또는 세부 정보에 불일치 사항이 발견되거나 어떤 제안을 수락해야 할지 확신할 수 없는 경우 해당 제안을 수락하지 마세요. 자세한 내용은 NetApp 계정팀에 문의하세요.

====
[NOTE]
====
이미 활성화된 PAYGO 구독이나 수정된 ​​비공개 제안이 있는 경우 승인 단계만 수행하면 됩니다. 이런 경우, 마켓플레이스는 동일한 목록 내에서 플랜을 업데이트하고 동일한 구독 ID를 유지하므로 콘솔의 구독 연결은 그대로 유지됩니다.

====
.단계
. NetApp 영업팀에서 제공한 비공개 제안 활성화 링크를 클릭하세요. 링크는 다음과 비슷하게 보여야 합니다.
`https://console.cloud.google.com/marketplace/private-offers/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeee`
. Google Cloud Marketplace로 리디렉션되어 상품 세부 정보를 검토할 수 있습니다.
+
.. **청구 계정**
.. **제품**: NetApp Console
.. **제안 세부 정보**
.. **가격**
+
[NOTE]
====
계획 세부 사항, 기간 및 가격을 주의 깊게 검토하세요. 무엇인가 잘못된 것이 있다면 제안을 수락하지 마세요. 수정 사항이 필요하면 NetApp 계정 팀에 문의하세요.

====


. 정보가 정확한지 확인하고 약관에 동의한 후 **동의**를 클릭하세요.
. 구독이 생성되는 동안 로딩 아이콘이 나타납니다.
. 구독이 성공적으로 생성되면 팝업 창이 표시됩니다. *주문 요청이 NetApp, Inc.로 전송되었습니다.*
. **NETAPP, Inc.에 등록**을 클릭하세요. 구독 구성을 완료하기 위해 NetApp Console 로 리디렉션됩니다. 귀하의 조직 내 다른 개인이 비공개 제안을 수락한 경우:
+
.. Google Cloud Marketplace에서 **주문**으로 이동합니다.
.. 상태가 **보류**인 제안을 찾으세요.
.. 3개 점 메뉴를 클릭하고 ** NetApp, Inc.에 등록**을 선택하세요.


. 당신은 다음으로 리디렉션됩니다 `https://console.netapp.com` 그리고 로그인하라는 메시지가 나타났습니다.
. 로그인 후, 다음으로 이동됩니다. `https://console.netapp.com/licenses/overview` . 다음 작업을 수행해야 하는 팝업이 표시됩니다.
+
.. *SaaS 마켓플레이스 구독*에 대한 표시 이름을 입력하세요.
.. 구독에 액세스할 수 있는 콘솔 **계정**을 선택하세요.
.. 선택적으로, 하나의 콘솔 계정에서 기존 Marketplace 구독을 자동으로 교체하려면 **기존 구독 교체**를 활성화할 수 있습니다.
+
[NOTE]
====
*** 이 대체 옵션은 단일 콘솔 계정으로 제한됩니다.
*** 여러 콘솔 계정을 동일한 마켓플레이스 구독에 연결해야 하는 경우 추가 계정을 수동으로 구성해야 합니다.


====


. **연계**를 클릭하세요.
. 구독을 콘솔 조직과 연결하려면 양식을 작성하세요.  그런 다음 **연결**을 클릭합니다.
. 구독을 연결한 후 **결제 기본 설정** 탭으로 이동하여 선택하세요.
. 마켓플레이스 구독 옵션을 검토하세요.
. 청구하려는 마켓플레이스 구독을 선택하세요.  이는 옵션이 두 개 이상인 경우에만 적용됩니다.
. **변경 사항 저장**을 선택합니다.
. 여러 하이퍼스케일러에 걸쳐 여러 구독이 있는 경우 필요에 따라 이 단계를 반복합니다.


마켓플레이스 구독 및 직접 라이선스 청구에 대한 자세한 내용은 다음을 참조하세요. link:https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["청구 환경 설정 문서"].
