---
sidebar: sidebar 
permalink: task-manage-data-services-licenses.html 
keywords: data services, byol, cloud backup, cloud tiering, data sense, cloud data sense, obtain license file, nlf, add license, update license, bluexp, netapp console, classification, tiering, backup and recovery, disaster recovery 
summary: 'NetApp 데이터 서비스와 함께 사용하기 위해 NetApp 에서 직접 구매한 라이선스(BYOL)를 관리합니다.  사용된 라이선스 용량, 남은 무료 용량을 볼 수 있으며, 용량 한도 또는 만료 날짜에 도달하면 알림이 표시됩니다.' 
---
= NetApp 데이터 서비스에 대한 라이선스 관리
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 포함한 NetApp 데이터 서비스와 함께 사용하기 위해 NetApp 에서 직접 구매한 라이선스(BYOL)를 관리할 수 있습니다.  사용된 라이선스 용량, 남은 무료 용량을 확인할 수 있으며, 용량 한도에 도달하거나 만료일이 되면 알림이 표시됩니다.


NOTE: *직접 라이선스* 페이지에는 모든 라이선스가 나열되어 있습니다.  특정 데이터 서비스에 대한 라이선스 세부 정보를 원하시면 *개요* 대시보드에서 데이터 서비스 타일을 사용하세요. link:task-homepage.html#overview-page["개요 대시보드에 대해 자세히 알아보세요"] .

이 페이지의 지침은 각 서비스에 적용되는 정보를 제공합니다.  이러한 서비스에 대한 라이선싱에 대한 자세한 내용은 다음 페이지를 참조하세요.

* https://docs.netapp.com/us-en/bluexp-backup-recovery/br-start-licensing.html["BlueXP backup and recovery 에 대한 라이선싱 설정"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/get-started/dr-licensing.html["BlueXP disaster recovery 위한 라이선싱 설정"^]
* https://docs.netapp.com/us-en/bluexp-ransomware-protection/rp-start-licenses.html["BlueXP ransomware protection 위한 라이선싱 설정"^]
* https://docs.netapp.com/us-en/bluexp-tiering/task-licensing-cloud-tiering.html["BlueXP tiering 에 대한 라이선싱 설정"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html["Cloud Volumes ONTAP 에 대한 라이선싱 설정"^]




== 라이센스 파일을 얻으세요

<stdin>에 해결되지 않은 지시어 - include::_include/task-obtain-license.adoc[]



== 라이센스 추가

<stdin>에 해결되지 않은 지시어 - include::_include/task-add-license.adoc[]



== 라이센스 업데이트

<stdin>에 해결되지 않은 지시어 - include::_include/task-update-license.adoc[]



== 라이센스 상태 보기

<stdin>에 해결되지 않은 지시어 - include::_include/task-view-license-status.adoc[]
