---
sidebar: sidebar 
permalink: task-homepage.html 
keywords: license, licensing, dashboard, capacity license, capacity based license, add license, install license, bluexp, netapp console, cloud volumes ontap license, cloud volumes ontap 
summary: 콘솔의 개요 대시보드에서 조직의 모든 구독 및 라이선스에 대한 개요를 확인하세요. 
---
= 대시보드 개요 사용
:allow-uri-read: 




== 대시보드 개요 사용

[role="lead"]
콘솔의 *개요* 대시보드를 사용하여 라이선스 및 구독 상태를 모니터링하여 구독이 만료일이나 용량 제한에 도달하더라도 비용을 관리하고 서비스를 유지할 수 있습니다.

각 데이터 서비스( Cloud Volumes ONTAP 포함)에 대한 구체적인 라이선스 및 구독 정보를 보고 각 서비스에 대한 세부 정보를 자세히 알아볼 수 있습니다.

또한, 다가오는 용량 제한이나 만료에 대한 알림을 받고 조치를 취하라는 메시지가 표시됩니다.



=== 특정 데이터 서비스에 대한 세부 정보 보기

*개요* 대시보드에서는 다음 데이터 서비스에 대한 세부 정보를 볼 수 있습니다.

* Cloud Volumes ONTAP
* 재해 복구
* 랜섬웨어 복원력
* 백업 및 복구
* 클라우드 티어링


예를 들어, Cloud Volumes ONTAP 리소스를 관리하는 업무를 맡은 관리자는 각 라이선스 또는 구독의 현재 용량을 볼 수 있으며, 이를 통해 자신의 관할 범위 내의 리소스를 집중적으로 볼 수 있습니다.


NOTE: 대시보드에서 라이선스를 업데이트하고 제거할 수는 있지만, 새로운 라이선스나 구독을 추가할 수는 없습니다.

link:task-manage-data-services-licenses.html["라이선스 관리에 대해 자세히 알아보세요"^] . link:task-manage-subscriptions.html["구독 관리에 대해 자세히 알아보세요"^] .

.단계
. NetApp 콘솔 메뉴에서 *거버넌스 > 라이선스 및 구독*을 선택합니다.
. *개요*를 선택하세요.
. 각 데이터 서비스( Cloud Volumes ONTAP 포함)에 대한 *보기*를 선택하면 세부 정보를 보고 라이선스와 구독을 관리할 수 있습니다.
+
각 타일은 용량에 대한 그래픽 개요를 제공합니다.  해당 용량에 대한 결제 방법을 보고 관리하려면 세부 정보 페이지를 확인하세요.

. *라이선스* 또는 *구독* 탭을 선택하세요.
. 열 필터와 필터링 기준 값을 선택하여 표를 필터링합니다.  예를 들어, *구독* 탭에서 유형 열을 연간 계약 또는 구독으로 필터링할 수 있습니다.
. 표에 표시된 열을 사용자 정의합니다.  *열* 아이콘을 선택하여 표시하거나 숨기려는 열을 지정하여 표에 열을 추가하거나 제거할 수 있습니다.
. 행을 확장하면 구독이나 라이선스에 포함된 내용, 구매한 용량, 약관 등의 세부 정보를 볼 수 있습니다.
. 작업 메뉴를 사용하면 라이선스 업데이트나 구독을 다른 조직과 연결하는 등 특정 라이선스나 구독을 관리할 수 있습니다.
+
특정 서비스에 대한 *개요* 페이지에서는 새로운 라이선스나 구독을 추가할 수 없습니다.  *직접 라이선스* 탭이나 *마켓플레이스 구독* 탭에서만 라이선스나 구독을 추가할 수 있습니다.

+
link:task-data-services-licenses.html["라이선스 관리에 대해 자세히 알아보세요."] link:task-manage-subscriptions.html["구독 관리에 대해 자세히 알아보세요."]





=== 라이센스 또는 구독 문제 해결

해결해야 할 라이선스 및 구독 문제를 볼 수 있습니다.  문제에는 라이센스 및 구독이 만료되거나 용량 한도에 도달하는 경우가 포함됩니다.

. NetApp 콘솔 메뉴에서 *거버넌스 > 라이선스 및 구독*을 선택합니다.
. *개요*를 선택하세요.
. 조정이 필요한 문제를 보려면 *조치 필요* 타일에서 *해결*을 선택하세요.  *해결*이 표시되지 않으면 현재 조치가 필요한 문제가 없습니다.
. *작업 필요* 페이지에서 *라이선스* 탭이나 *구독* 탭을 선택합니다.
. 문제를 해결하려면 작업 메뉴를 사용하세요.
+
link:task-manage-data-services-licenses.html["라이선스 관리에 대해 자세히 알아보세요"^] . link:task-manage-subscriptions.html["구독 관리에 대해 자세히 알아보세요"^] .


